name: deploy

on:
  push:
    branches:
      - main # substitua pelo nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1 # use a versão Node.js que você precisa

      - name: Install Dependencies
        run: npm install # ou yarn install, dependendo do seu gerenciador de pacotes

      - name: Build
        run: npm run build # ou yarn build, dependendo do seu gerenciador de pacotes

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # caminho para a pasta de build

